package com.storeanalytics.common.web;

public enum ApiErrorCode {
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    INVALID_ARGUMENT,
    MISSING_PARAMETER,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    RESOURCE_NOT_FOUND,
    CONCURRENT_MODIFICATION,
    INTERNAL_ERROR,
    INVALID_CREDENTIALS,
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    SESSION_EXPIRED
}
