#!/usr/bin/env bash
set -Eeuo pipefail
set +x
umask 077
readonly TEST_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${TEST_DIR}/../../deploy/bin/release-safety.sh"
temporary_directory="$(mktemp -d)"
trap 'rm -rf -- "${temporary_directory}"' EXIT
configuration="${temporary_directory}/release.env"
count=0
accept() {
  printf '%s\n' "$@" >"${configuration}"
  release_validate_historical_sales_configuration "${configuration}" >/dev/null 2>&1
  count=$((count + 1))
}
reject() {
  printf '%s\n' "$@" >"${configuration}"
  if release_validate_historical_sales_configuration "${configuration}" >/dev/null 2>&1; then
    printf 'HISTORICAL SALES RELEASE SAFETY: unexpected acceptance\n' >&2
    exit 1
  fi
  count=$((count + 1))
}
accept ''
accept SYNC_HISTORICAL_SALES_ENABLED=false SYNC_HISTORICAL_SALES_START_DATE=2026-10-01
accept SYNC_HISTORICAL_SALES_ENABLED=true SYNC_HISTORICAL_SALES_START_DATE=2026-10-01 SYNC_SCHEDULE_ENABLED=true
accept SYNC_HISTORICAL_SALES_ENABLED=true SYNC_HISTORICAL_SALES_START_DATE=2024-02-29 SYNC_SCHEDULE_ENABLED=true SYNC_HISTORICAL_SALES_WINDOW_MINUTES=15 SYNC_HISTORICAL_SALES_MAX_REQUESTS_PER_STEP=1 SYNC_HISTORICAL_SALES_MAX_REQUESTS_PER_DAY=1 SYNC_HISTORICAL_SALES_CYCLE_INTERVAL=1h SYNC_HISTORICAL_SALES_ENQUEUE_DELAY=30s
reject SYNC_HISTORICAL_SALES_ENABLED=yes
reject SYNC_HISTORICAL_SALES_ENABLED=true SYNC_SCHEDULE_ENABLED=true
reject SYNC_HISTORICAL_SALES_ENABLED=true SYNC_HISTORICAL_SALES_START_DATE=2026-10-01
reject SYNC_HISTORICAL_SALES_ENABLED=true SYNC_HISTORICAL_SALES_START_DATE=2026-10-01 SYNC_SCHEDULE_ENABLED=true SYNC_WORKER_ENABLED=false
reject SYNC_HISTORICAL_SALES_START_DATE=2026-02-29
reject SYNC_HISTORICAL_SALES_START_DATE=2026-13-01
reject 'SYNC_HISTORICAL_SALES_START_DATE=$(touch /tmp/should-never-be-created)'
reject SYNC_HISTORICAL_SALES_WINDOW_MINUTES=14
reject SYNC_HISTORICAL_SALES_WINDOW_MINUTES=181
reject SYNC_HISTORICAL_SALES_WINDOW_MINUTES=99999999999999999999
reject SYNC_HISTORICAL_SALES_MAX_REQUESTS_PER_STEP=101
reject SYNC_HISTORICAL_SALES_MAX_REQUESTS_PER_DAY=201
reject SYNC_HISTORICAL_SALES_MAX_REQUESTS_PER_STEP=20 SYNC_HISTORICAL_SALES_MAX_REQUESTS_PER_DAY=19
reject SYNC_HISTORICAL_SALES_CYCLE_INTERVAL=59m
reject SYNC_HISTORICAL_SALES_CYCLE_INTERVAL=32d
reject SYNC_HISTORICAL_SALES_CYCLE_INTERVAL=-1h
reject SYNC_HISTORICAL_SALES_ENQUEUE_DELAY=0s
reject SYNC_HISTORICAL_SALES_ENQUEUE_DELAY=garbage
printf 'HISTORICAL SALES RELEASE SAFETY: %s cases passed\n' "${count}"
