server:
  servlet:
    session:
      cookie:
        secure: true

logging:
  level:
    root: INFO
    com.storeanalytics: INFO
    org.springframework.security: WARN

spring:
  jpa:
    show-sql: false

app:
  security:
    secure-cookies: true
  livesklad:
    require-https: true
