package com.storeanalytics.audit.service;

public enum AuditAction {
    PERFORMANCE_PLAN_CHANGED,
    WORK_SCHEDULE_REPLACED,
    EMPLOYEE_RATING_PARTICIPATION_CHANGED,
    EMPLOYEE_RATING_FINALIZED,
    RATING_SCHEME_CREATED,
    PAYROLL_SCHEME_CREATED,
    ANALYTICS_PRODUCT_CLASSIFIED,
    PAYROLL_PRODUCT_CLASSIFIED,
    PAYROLL_CALCULATED,
    PAYROLL_RECALCULATED,
    PAYROLL_REVISION_CREATED,
    PAYROLL_ADJUSTMENT_CREATED,
    PAYROLL_ADJUSTMENT_VOIDED,
    PAYROLL_APPROVED,
    MONTHLY_REPORT_FINALIZED,
    ANNUAL_REPORT_FINALIZED,
    REPORT_BACKFILL_REQUESTED,
    PAYROLL_PAID,
    USER_CREATED,
    USER_CHANGED,
    USER_STORE_ACCESS_CHANGED,
    USER_PASSWORD_RESET,
    MANUAL_SYNC_STARTED,
    SYNC_JOB_CANCELLATION_REQUESTED
}
